In [1]:
import numpy as np
import scipy
import cdd

In [ ]:
points = np.array([[0, 0], [0, 1], [1, 1], [1, 0]])
b = np.ones(len(points))
mat = cdd.matrix_from_array(
    np.column_stack((b, points)), rep_type=cdd.RepType.GENERATOR
)
poly = cdd.polyhedron_from_matrix(mat)
ext = cdd.copy_inequalities(poly)
array = np.array(ext.array)
b = array[:, 0]
A = array[:, 1:]
print(ext)
equations = b + A @ points.T

H-representation
begin
 4 3 real
  0  0  1
  0  1  0
  1  0 -1
  1 -1  0
end


In [ ]:
A @ points.T + b.repeat(4).reshape(4, 4)

array([[0., 1., 1., 0.],
       [0., 0., 1., 1.],
       [1., 0., 0., 1.],
       [1., 1., 0., 0.]])

In [47]:
b

array([0., 0., 1., 1.])

In [ ]:
b.repeat(4).reshape(4, 4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
def get_simplices_cdd(vertices):
    mat = cdd.matrix_from_array(
        np.column_stack((np.ones(len(vertices)), vertices)),
        rep_type=cdd.RepType.GENERATOR,
    )
    poly = cdd.polyhedron_from_matrix(mat)
    ext = cdd.copy_inequalities(poly)
    b = np.array(ext.array)[:, 0]
    A = np.array(ext.array)[:, 1:]
    num_equations = A.shape[0]
    equation_results = A @ vertices.T + b[:,None]
    zero_indices = np.argwhere(np.isclose(equation_results, 0.0))
    for i in range(num_equations):
        results = zero_indices[zero_indices[:, 0] == i]
        