In [ ]:
import numpy as np


def rref(A: np.ndarray) -> np.ndarray:
    A = A.astype(float)  # ensure floating-point math
    
    rows, cols = A.shape
    pivot_row = 0

    for col in range(cols):
        if pivot_row >= rows:
            break
        
        # Find pivot in this column (first nonzero entry at or below pivot_row)
        nonzero = np.where(~np.isclose(A[pivot_row:, col], 0))[0]
        if nonzero.size == 0:
            continue
        
        pivot = pivot_row + nonzero[0]

        # Swap pivot row upward
        if pivot != pivot_row:
            A[[pivot_row, pivot]] = A[[pivot, pivot_row]]

        # Normalize pivot row
        A[pivot_row] = A[pivot_row] / A[pivot_row, col]

        # Eliminate all other rows
        for r in range(rows):
            if r != pivot_row:
                factor = A[r, col]
                A[r] -= factor * A[pivot_row]

        pivot_row += 1

    return A

In [7]:
print(rref(np.array([[-2,2,-1,2],[0,3,3,-3],[1,-4,2,2]],dtype=np.float64)))
print(rref(np.array([[4,-3,-4,-2],[-4,2,1,-4],[-1,-3,1,-4]],dtype=np.float64)))


[[ 1.  0.  0. -2.]
 [ 0.  1.  0. -1.]
 [ 0.  0.  1.  0.]]
[[ 1.   0.   0.   2. ]
 [-0.   1.   0.   1.2]
 [ 0.   0.   1.   1.6]]


In [8]:
print(rref(np.array([[1,1,1,12],[1,2,4,15],[1,3,9,16]])))

[[ 1.  0.  0.  7.]
 [ 0.  1.  0.  6.]
 [ 0.  0.  1. -1.]]


In [12]:
np.linalg.inv(np.array([[6,-3,0],[-3,29,-10],[0,-9,21]])) @ np.array([1,0,1])

array([0.18769231, 0.04205128, 0.06564103])

In [11]:
-509/2865-2/191

-0.18813263525305413